apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

images:
- digest: sha256:c742b1cccc5a69abd082b1d61c8ef616a27699b6b52430ac700019f22800c06f
  name: manager
  newName: localhost:5000/porterops-controller
