apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: porter-agent
  labels:
    getporter.org/generator: "porter-operator-bundle"
  namespace: '{{ .Release.Namespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: porter-operator-agent-role
subjects:
  - kind: ServiceAccount
    name: porter-agent
    namespace: '{{ .Release.Namespace }}'
