# permissions for end users to view installationoutputs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: installationoutput-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: porter-operator
    app.kubernetes.io/part-of: porter-operator
    app.kubernetes.io/managed-by: kustomize
  name: installationoutput-viewer-role
rules:
- apiGroups:
  - getporter.org
  resources:
  - installationoutputs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - getporter.org
  resources:
  - installationoutputs/status
  verbs:
  - get
