# permissions for end users to edit parametersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parameterset-editor-role
rules:
- apiGroups:
  - porter.sh
  resources:
  - parametersets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - porter.sh
  resources:
  - parametersets/status
  verbs:
  - get
