# permissions for end users to view parametersets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: parameterset-viewer-role
rules:
- apiGroups:
  - porter.sh
  resources:
  - parametersets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - porter.sh
  resources:
  - parametersets/status
  verbs:
  - get
