# You can configure the mage bump command to use a local build of porter
# build with mage XBuildAll LocalPorterAgentBuild
# export PORTER_AGENT_REPOSITORY=localhost:5000/porter-agent
# export PORTER_AGENT_VERSION=canary-dev
schemaVersion: 1.0.1
name: dev-build
parameters:
  - name: porterRepository
    source:
      env: PORTER_AGENT_REPOSITORY
  - name: porterVersion
    source:
      env: PORTER_AGENT_VERSION
  - name: pullPolicy
    source:
      value: "Always"
