apiVersion: porter.sh/v1
kind: PorterConfig
metadata:
  name: default
spec:
  debug: true
  debugPlugins: true
  default-secrets-plugin: "kubernetes.secrets"
  default-storage: "in-cluster-mongodb"
  storage:
    - name: "in-cluster-mongodb"
      plugin: "mongodb"
      config:
        url: "mongodb://mongodb.porter-operator-system.svc.cluster.local"