apiVersion: porter.sh/v1
kind: Installation
metadata:
  name: porter-hello
spec:
  schemaVersion: 1.0.0
  targetNamespace: operator
  installationName: porter-hello
  bundleRepository: getporter/porter-hello
  bundleVersion: 0.1.1
