apiVersion: porter.sh/v1
kind: Installation
metadata:
  name: porter-hello
  labels:
    porter.sh/testdata: "true"
spec:
  schemaVersion: 1.0.0
  namespace: operator
  name: hello
  bundle:
    repository: getporter/porter-hello
    version: 0.1.1
