apiVersion: porter.sh/v1
kind: Installation
metadata:
  name: porter-hello
  labels:
    porter.sh/testdata: "true"
spec:
  schemaVersion: 1.0.2
  namespace: operator
  name: hello
  bundle:
    repository: ghcr.io/getporter/test/porter-hello
    version: 0.2.0
  parameters:
    name: llamas 
